language: dart
dart:
  - stable
with_content_shell: true

# sudo: false

# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache
    - $HOME/.chrome/canary
    - node_modules

before_install:
  - pub global activate test_runner
  - pub global activate dart_coveralls
# - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - chmod +x ./tool/*.sh

# https://pub.dartlang.org/packages/test_runner
# pub global activate test_runner
# pub global run test_runner --disable-ansi --skip-browser-tests
# or run_tests

script: ./tool/travis.sh
