name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 0.9.2+0
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: any

dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  logging: '>=0.11.2 <0.12.0'
  fixnum: '>=0.9.1+2 <0.10.0'
  protobuf: '>=0.5.0 <0.6.0'
  uuid: '>=0.5.0 <0.6.0'
  intl:  '>=0.12.4+2 <0.13.0'

dev_dependencies:
  test: '>=0.12.4+9'
