name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 1.0.0
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: '>=1.13.0'

dependencies:
  browser: '>=0.10.0+2'
  fixnum: '>=0.10.2'
  intl:  '>=0.12.5'
  logging: '>=0.11.2'
  protobuf: '>=0.5.0'
  stack_trace: '>=1.5.0'
  uuid: '>=0.5.0'
  charted: '>= 0.3.0'
#    path: /Users/jorg/Documents/BizPlatform/lightning/charted

dev_dependencies:
  test: '>=0.12.6'

transformers:
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
