name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 0.9.0+0
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: ">=0.10.0"
  logging: ">=0.11.1"
  fixnum: ">=0.9.1+2"
  intl:  ">=0.12.4"
  protobuf: ">=0.4.2"
  stack_trace: any
  uuid: any

dev_dependencies:
  test: '>=0.12.4'
