name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 2.1.3
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

# https://www.dartlang.org/install/archive
environment:
  sdk: '1.20.1'

dependencies:
  browser: any
  fixnum: any
  intl:  any
  logging: any
  protobuf: any
  stack_trace: any
  usage: any
  uuid: any
# https://pub.dartlang.org/packages/charted 0.4.0+1
  charted:
    git: git@github.com:accorto/charted.git # observe breaking change fix

dev_dependencies:
  test: any
  intl_translation: any

transformers:
- $dart2js:
    suppressHints: false
    suppressWarnings: false
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
