name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 2.1.3
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: '1.19.1'

dependencies:
  browser: any
  fixnum: any
  intl:  any
  logging: any
  protobuf: any
  stack_trace: any
  usage: any
  uuid: any
  charted:
    git: git@github.com:accorto/charted.git # observe breaking change fix

dev_dependencies:
  test: any

transformers:
- $dart2js:
    suppressHints: false
    suppressWarnings: false
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
