name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 0.9.2+0
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: any

dependencies:
  browser: any
  logging: any
  fixnum: any
  intl:  any
  protobuf: 0.4.2
  stack_trace: any
  uuid: any

dev_dependencies:
  test: any
