name: lightning_dart
description: Lightning Dart Components based on SLDS CSS - https://github.com/accorto/lightning-dart/wiki
version: 0.5.2
author: Accorto <support@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  logging: any
  fixnum: any
  intl: any
  protobuf: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
