name: lightning
description: Lightning Dart UI Components based on Salesforce Lightning Design System
version: 2.0.2
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com
documentation:

environment:
  sdk: '1.16.0' # Charted does not work with 1.17.x

dependencies:
  browser: '>=0.10.0+2'
  fixnum: '>=0.10.5'
  intl:  '>=0.13.0'
  logging: '>=0.11.3'
  protobuf: '>=0.5.2 <0.6.0'
  stack_trace: '>=1.6.6'
  uuid: '>=0.5.3'
  charted: '>= 0.4.0'
  #  path: /Users/jorg/Documents/BizPlatform/lightning/charted # local copy

dev_dependencies:
  test: '>=0.12.14'

transformers:
- $dart2js:
    suppressHints: false
    suppressWarnings: false
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
